config/routes.rb
Rails.application.routes.draw do
  get 'archives/index'
  resources :entries
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'entries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :calories, :proteins, :carbohydrates, :fats, :meal_type, presence: true
  validates :calories, :proteins, :carbohydrates, :fats, numericality: true

  def day
    self.created_at.strftime(Entry.date_format)
  end

  def self.date_format
    # Here %B stands for readable month
    '%d %B, %Y'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    # `&:method_name` is basically a call to an instance method on self
    # `group_by` groups similar entries into one array
    @entries = Entry.all.group_by(&:day)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.where(created_at: Time.current.all_day)
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_readable_date(date = DateTime.now)
    date.strftime(Entry.date_format)
  end

  def load_svg(path)
    File.open("app/assets/images/svg/#{path}", 'rb') do |file|
      raw file.read
    end
  end
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archives/index.html.erb
<div class="columns is-centered">
  <div class="column is-half">
    <% @entries.each do |day, day_entries| %>
      <h3 class="is-size-4 has-text-weight-bold mt-6 mb-4 text-centered">Entries for <%= day %></h3>
      <nav class="level is-mobile">
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Calories</p>
            <!--
              Pluck grabs a specified key from an array of hashes
              Example:
              3.0.0 :029 > test_arr = [{test: 12, test2: 34}, { test: 23, test2: 56}]
              => [{:test=>12, :test2=>34}, {:test=>23, :test2=>56}]
              3.0.0 :030 > test_arr.pluck(:test)
              => [12, 23]
              3.0.0 :031 > test_arr.pluck(:test).sum
              => 35
              3.0.0 :032 > test_arr.pluck(:test2).sum
              => 90
            -->
            <p class="title"><%= day_entries.pluck(:calories).sum %></p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Proteins</p>
            <p class="title"><%= day_entries.pluck(:proteins).sum %>g</p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Carbohydrates</p>
            <p class="title"><%= day_entries.pluck(:carbohydrates).sum %>g</p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Fats</p>
            <p class="title"><%= day_entries.pluck(:fats).sum %>g</p>
          </div>
        </div>
      </nav>
      <% day_entries.each do |entry| %>
        <%= link_to entry_path(entry), class: 'is-link' do %>
          <div class="card">
            <div class="card-content">
              <p class="has-text-weight-bold"><%= entry.meal_type %></p>
              <%= entry.calories %> calories,
              <%= entry.proteins %>g protein,
              <%= entry.carbohydrates %>g carbs,
              <%= entry.fats %>g fat
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>
      <div class="message-body">
        <ul>
          <% entry.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meal_type, class: 'label' %>
    <%= form.text_field :meal_type, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :calories, class: 'label' %>
    <%= form.number_field :calories, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :proteins, class: 'label' %>
    <%= form.number_field :proteins, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :carbohydrates, class: 'label' %>
    <%= form.number_field :carbohydrates, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :fats, class: 'label' %>
    <%= form.number_field :fats, class: 'input' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'button is-success' %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="columns mt-6 is-centered">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3">Editing Entry</h1>
    <%= render 'form', entry: @entry %>
  </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  Foodlog - <%= formatted_readable_date %>
<% end %>

<div class="columns mt-6 is-centered">
  <% @entries.each do |entry| %>
    <div class="column is-one-quarter">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title"><%= entry.meal_type %></p>
        </header>
        <div class="card-content">
          <div class="content">
            <p>
              <span class="has-text-weight-bold">
                <%= entry.calories %>
              </span> calories
            </p>
            <p>
              <span class="has-text-weight-bold">
                <%= entry.proteins %>
              </span> grams of protein
            </p>
            <p>
              <span class="has-text-weight-bold">
                <%= entry.carbohydrates %>
              </span> grams of carbohydrates
            </p>
            <p>
              <span class="has-text-weight-bold">
                <%= entry.fats %>
              </span> grams of fat
            </p>
            <p class="italic">Logged <%= time_ago_in_words(entry.created_at) %> ago</p>
          </div>
        </div>
        <div class="card-footer">
          <%= link_to 'View', entry, class: 'card-footer-item' %>
          <%= link_to 'Edit', edit_entry_path(entry), class: 'card-footer-item' %>
          <%= link_to 'Delete', entry, method: :delete, data: { confirm: 'Are you sure?' }, class: 'card-footer-item' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="columns mt-6 is-centered">
  <%= link_to 'View all entries by day', archives_index_path, class: 'button is-link is-outlined is-centered' %>
</div>

app/views/entries/new.html.erb
<div class="columns mt-6 is-centered">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3">New Entry</h1>
    <%= render 'form', entry: @entry %>
  </div>
</div>

app/views/entries/show.html.erb
<% content_for :title do %>
  <%= @entry.meal_type %> - <%= formatted_readable_date(@entry.created_at) %>
<% end %>

<div class="columns mt-6 is-centered">
  <div class="column is-one-third">
    <nav class="panel is-link">
      <p class="panel-heading"><%= @entry.meal_type %></p>
      <div class="panel-block">
        Calories: <%= @entry.calories %>
      </div>

      <div class="panel-block">
        Proteins: <%= @entry.proteins %>g
      </div>

      <div class="panel-block">
        Carbohydrates: <%= @entry.carbohydrates %>g
      </div>

      <div class="panel-block">
        Fats: <%= @entry.fats %>g
      </div>
    </nav>

    <div class="columns is-mobile">
      <div class="column">
        <%= link_to 'Edit', edit_entry_path(@entry), class: 'button is-gray' %>
        <%= link_to 'Delete', entry_path(@entry), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-danger ml-2' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <% if notice.present? %>
      <div id="notice" class="notification is-link is-light"><%= notice %></div>
    <% end %>

    <% if alert.present? %>
      <div id="alert" class="notification is-danger is-light"><%= alert %></div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<header class="hero is-link is-small shared-header">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to root_path, class: 'navbar-item' do %>
            <%= load_svg('logo.svg') %>
            <span class="has-text-weight-bold is-size-4 ml-4">Foodlog</span>
          <% end %>
          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <span class="navbar-item">
              <%= link_to 'Create new entry', new_entry_path, class: 'button is-success' %>
            </span>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <% if content_for(:title) %>
          <%= yield :title %>
        <% else %>
          Foodlog
        <% end %>
      </h1>
    </div>
  </div>
</header>